# Generated by Django 5.2.4 on 2026-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
